version: "2"

run:
  build-tags:
    - duckdb_arrow

linters:
  enable:
    - bodyclose
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    misspell:
      locale: US
  exclusions:
    presets: []
