{{- if .Values.gateway.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "duckflight.fullname" . }}-sticky
  labels:
    {{- include "duckflight.labels" . | nindent 4 }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: GRPCRoute
      name: {{ include "duckflight.fullname" . }}
  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: Header
      header:
        name: authorization
{{- end }}
