apiVersion: v1
kind: Service
metadata:
  name: {{ include "duckflight.fullname" . }}
  labels:
    {{- include "duckflight.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 31337
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "duckflight.selectorLabels" . | nindent 4 }}
