name: Release

on:
  push:
    tags: ["v*"]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t duckflight:ci -f Dockerfile .
