name: Release Helm

on:
  push:
    tags: ["helm/v*"]

env:
  REGISTRY: ghcr.io

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Helm lint
        run: helm lint helm/duckflight/

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Set chart version from tag
        run: |
          VERSION="${GITHUB_REF_NAME#helm/v}"
          yq -i ".version = \"${VERSION}\"" helm/duckflight/Chart.yaml
          yq -i ".appVersion = \"${VERSION}\"" helm/duckflight/Chart.yaml

      - name: Helm package
        run: helm package helm/duckflight/

      - name: Push chart to GHCR
        run: helm push duckflight-*.tgz oci://${{ env.REGISTRY }}/fairtier/charts
